services:
  # web:
  #   build: .
  #   container_name: flask_shop
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db

  postgres:
    image: ankane/pgvector:latest
    container_name: postgres_shop
    restart: always
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shop_db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

volumes:
  postgres_data:


